// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log({
      foo: "yay"
    });

console.log({
      bar: 33
    });

console.log({
      foo: "yay",
      bar: 33
    });

console.log({ });

/*  Not a pure module */
