// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var players = /* array */[
  {
    name: "Amy",
    scores: /* array */[
      1,
      2,
      3
    ]
  },
  {
    name: "Brolinho",
    scores: /* array */[
      4,
      5,
      6
    ]
  }
];

players.forEach((function (player, i) {
        console.log(i, player.name);
        console.log("First score:", Caml_array.caml_array_get(player.scores, 0));
        return /* () */0;
      }));

exports.players = players;
/*  Not a pure module */
