// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var myFunc_ = (
  function (x) {
    return `${x} is a ${typeof x}`
  }
);

console.log(myFunc_("Foo"));

console.log(myFunc_("Bar!"));

console.log(myFunc_("Baz"));

console.log(myFunc_("Cowpoke?"));

exports.myFunc_ = myFunc_;
/* myFunc_ Not a pure module */
