// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var object_ = (
  {
    value: {
      name: 'Rolling Rocket Thundernauts',
      rank: 11,
    },
    onChange: (v, n) => {
      console.log('Inside onChange:', v.name, v.rank, n + 1)
    }
  }
);

console.log(object_);

console.log(object_.value.name);

var func = object_.onChange;

Curry._2(func, object_.value, 55);

exports.object_ = object_;
exports.func = func;
/* object_ Not a pure module */
