// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';


var props = {
  title: "Woo",
  size: {
    w: 100,
    h: 200
  }
};

console.log(props);

exports.props = props;
/*  Not a pure module */
