// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var b = "two";

console.log("Tuple values:", 1, b, 34.56);

var player1 = {
  name: "BurgerKingLizard",
  powerLevel: 9000.126,
  classes: /* :: */Caml_chrome_debugger.simpleVariant("::", [
      "NecroPaladin",
      /* :: */Caml_chrome_debugger.simpleVariant("::", [
          "NinjaBerserker",
          /* [] */0
        ])
    ]),
  location: {
    country: "tw",
    state: undefined
  }
};

var country = "tw";

var classes = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    "NecroPaladin",
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        "NinjaBerserker",
        /* [] */0
      ])
  ]);

var name = "BurgerKingLizard";

var state_ = undefined;

console.log("Record:\n", player1);

Curry._4(Printf.printf(/* Format */Caml_chrome_debugger.simpleVariant("Format", [
            /* String_literal */Caml_chrome_debugger.variant("String_literal", 11, [
                "name: ",
                /* String */Caml_chrome_debugger.variant("String", 2, [
                    /* No_padding */0,
                    /* String_literal */Caml_chrome_debugger.variant("String_literal", 11, [
                        ", powerLevel: ",
                        /* Float */Caml_chrome_debugger.variant("Float", 8, [
                            /* Float_f */0,
                            /* Lit_padding */Caml_chrome_debugger.variant("Lit_padding", 0, [
                                /* Right */1,
                                0
                              ]),
                            /* Lit_precision */Caml_chrome_debugger.simpleVariant("Lit_precision", [2]),
                            /* String_literal */Caml_chrome_debugger.variant("String_literal", 11, [
                                ", country: ",
                                /* String */Caml_chrome_debugger.variant("String", 2, [
                                    /* No_padding */0,
                                    /* String_literal */Caml_chrome_debugger.variant("String_literal", 11, [
                                        ", state: ",
                                        /* String */Caml_chrome_debugger.variant("String", 2, [
                                            /* No_padding */0,
                                            /* Char_literal */Caml_chrome_debugger.variant("Char_literal", 12, [
                                                /* "\n" */10,
                                                /* End_of_format */0
                                              ])
                                          ])
                                      ])
                                  ])
                              ])
                          ])
                      ])
                  ])
              ]),
            "name: %s, powerLevel: %0.2f, country: %s, state: %s\n"
          ])), name, 9000.126, country, Belt_Option.getWithDefault(undefined, "N/A"));

console.log("Classes:", classes);

var a = 1;

var c = 34.56;

var powerLevel = 9000.126;

var state = undefined;

exports.a = a;
exports.b = b;
exports.c = c;
exports.player1 = player1;
exports.name = name;
exports.powerLevel = powerLevel;
exports.classes = classes;
exports.country = country;
exports.state = state;
exports.state_ = state_;
/*  Not a pure module */
