// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var b = "two";

console.log("Tuple values:", 1, b, 34.56);

var country = "tw";

var classes = /* :: */[
  "NecroPaladin",
  /* :: */[
    "NinjaBerserker",
    /* [] */0
  ]
];

var name = "BurgerLizard";

Curry._4(Printf.printf(/* Format */[
          /* String_literal */Block.__(11, [
              "name: ",
              /* String */Block.__(2, [
                  /* No_padding */0,
                  /* String_literal */Block.__(11, [
                      ", powerLevel: ",
                      /* Float */Block.__(8, [
                          /* Float_f */0,
                          /* Lit_padding */Block.__(0, [
                              /* Right */1,
                              0
                            ]),
                          /* Lit_precision */[2],
                          /* String_literal */Block.__(11, [
                              ", country: ",
                              /* String */Block.__(2, [
                                  /* No_padding */0,
                                  /* String_literal */Block.__(11, [
                                      ", state: ",
                                      /* String */Block.__(2, [
                                          /* No_padding */0,
                                          /* Char_literal */Block.__(12, [
                                              /* "\n" */10,
                                              /* End_of_format */0
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ])
                ])
            ]),
          "name: %s, powerLevel: %0.2f, country: %s, state: %s\n"
        ]), name, 9000.126, country, Belt_Option.getWithDefault(/* None */0, "N/A"));

console.log("Classes:", classes);

var a = 1;

var c = 34.56;

var player1 = /* record */[
  /* name */"BurgerLizard",
  /* powerLevel */9000.126,
  /* classes : :: */[
    "NecroPaladin",
    /* :: */[
      "NinjaBerserker",
      /* [] */0
    ]
  ],
  /* location : record */[
    /* country */"tw",
    /* state : None */0
  ]
];

var powerLevel = 9000.126;

var state = /* None */0;

exports.a = a;
exports.b = b;
exports.c = c;
exports.player1 = player1;
exports.name = name;
exports.powerLevel = powerLevel;
exports.classes = classes;
exports.country = country;
exports.state = state;
/*  Not a pure module */
