// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function compute(param) {
  return Belt_Array.reduce(Belt_Array.keep(Belt_Array.range(1, 999), (function (x) {
                    if (x % 3 === 0) {
                      return true;
                    } else {
                      return x % 5 === 0;
                    }
                  })), 0, (function (prim, prim$1) {
                return prim + prim$1 | 0;
              }));
}

exports.compute = compute;
/* No side effect */
