// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function compute() {
  return Belt_Array.reduce(Belt_Array.keep(Belt_Array.range(1, 999), (function (x) {
                    var match = x % 3;
                    var match$1 = x % 5;
                    if (match !== 0) {
                      return match$1 === 0;
                    } else {
                      return true;
                    }
                  })), 0, (function (prim, prim$1) {
                return prim + prim$1 | 0;
              }));
}

exports.compute = compute;
/* No side effect */
