// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Axios = require("axios");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Helpers$HelloReason = require("./Helpers.bs.js");

function getAccessToken() {
  return Json_decode.field("eventbrite_access_token", Json_decode.string, Json.parseOrRaise(Fs.readFileSync("secrets.json", "utf8")));
}

var cfg = {
  params: {
    token: getAccessToken(/* () */0),
    "location.address": "2100 S Wentworth Ave, Chicago, IL 60616",
    "location.within": "1mi",
    sort_by: "date"
  }
};

Axios.get("https://www.eventbriteapi.com/v3/events/search", cfg).then((function (res) {
        console.log(res.status);
        var text = Helpers$HelloReason.prettyStringify(res.data);
        Fs.writeFileSync("results.json", text, "utf8");
        return Promise.resolve(true);
      }));

exports.getAccessToken = getAccessToken;
exports.cfg = cfg;
/* cfg Not a pure module */
