// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var ButtonDoc = {
  title: "Button",
  desc: "An interactive widget that executes a handler when you click it"
};

var TextDoc = {
  title: "Text",
  defaultFont: "monospace"
};

function printDoc(doc) {
  console.log(doc.title);
  return /* () */0;
}

List.iter(printDoc, /* :: */Caml_chrome_debugger.simpleVariant("::", [
        ButtonDoc,
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            TextDoc,
            /* [] */0
          ])
      ]));

var doc1 = ButtonDoc;

var doc2 = TextDoc;

exports.ButtonDoc = ButtonDoc;
exports.TextDoc = TextDoc;
exports.printDoc = printDoc;
exports.doc1 = doc1;
exports.doc2 = doc2;
/*  Not a pure module */
