// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function makeComponent(name) {
  return {
          name: name,
          render: (function (param) {
              return "";
            })
        };
}

function MakeDropdown(D) {
  var component_name = D.name;
  var component_render = function (param) {
    return "";
  };
  var component = {
    name: component_name,
    render: component_render
  };
  var make = function (_children) {
    return {
            name: D.name,
            render: (function (param) {
                return "<div />";
              })
          };
  };
  return {
          component: component,
          make: make
        };
}

var name = "PredatorDropdown";

function component_render(param) {
  return "";
}

var component = {
  name: name,
  render: component_render
};

function make(_children) {
  return {
          name: name,
          render: (function (param) {
              return "<div />";
            })
        };
}

var PredatorDropdown = {
  component: component,
  make: make
};

exports.makeComponent = makeComponent;
exports.MakeDropdown = MakeDropdown;
exports.PredatorDropdown = PredatorDropdown;
/* No side effect */
