// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';


function makeComponent(name) {
  return /* record */[
          /* name */name,
          /* render */(function () {
              return "";
            })
        ];
}

function MakeDropdown(D) {
  var component_000 = /* name */D[/* name */0];
  var component_001 = function () {
    return "";
  };
  var component = /* record */[
    component_000,
    component_001
  ];
  var make = function () {
    return /* record */[
            component_000,
            /* render */(function () {
                return "<div />";
              })
          ];
  };
  return /* module */[
          /* component */component,
          /* make */make
        ];
}

var name = "PredatorDropdown";

function component_001() {
  return "";
}

var component = /* record */[
  /* name */name,
  component_001
];

function make() {
  return /* record */[
          /* name */name,
          /* render */(function () {
              return "<div />";
            })
        ];
}

var PredatorDropdown = /* module */[
  /* component */component,
  /* make */make
];

exports.makeComponent = makeComponent;
exports.MakeDropdown = MakeDropdown;
exports.PredatorDropdown = PredatorDropdown;
/* No side effect */
