// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function MakeDelta(D) {
  var toMessage = function (current, previous) {
    var delta = Curry._2(D[/* subtract */0], current, previous);
    var match = Caml_obj.caml_compare(current, previous) === 1;
    var sign = match ? "+" : "";
    return Curry._1(D[/* toString */1], current) + (" (" + (sign + (Curry._1(D[/* toString */1], delta) + ")")));
  };
  return /* module */Block.localModule(["toMessage"], [toMessage]);
}

function toMessage(current, previous) {
  var delta = current - previous | 0;
  var match = Caml_obj.caml_compare(current, previous) === 1;
  var sign = match ? "+" : "";
  return String(current) + (" (" + (sign + (String(delta) + ")")));
}

var IntDelta = /* module */Block.localModule(["toMessage"], [toMessage]);

function toString(x) {
  return "$" + x.toFixed(2);
}

function toMessage$1(current, previous) {
  var delta = current - previous;
  var match = Caml_obj.caml_compare(current, previous) === 1;
  var sign = match ? "+" : "";
  return toString(current) + (" (" + (sign + (toString(delta) + ")")));
}

var MoneyDelta = /* module */Block.localModule(["toMessage"], [toMessage$1]);

console.log(toMessage(14, 15));

console.log(toMessage$1(12.35, 3.11));

exports.MakeDelta = MakeDelta;
exports.IntDelta = IntDelta;
exports.MoneyDelta = MoneyDelta;
/*  Not a pure module */
