// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';


function add5(x) {
  return x + 5 | 0;
}

function mult2(x) {
  return (x << 1);
}

console.log(9);

console.log(13);

console.log(18);

exports.add5 = add5;
exports.mult2 = mult2;
/*  Not a pure module */
