// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var mesg = ( '你好世界！' );

console.log(mesg);

var mesg2 = "再见宇宙！";

console.log(mesg2);

var mesg3 = "Last message: " + (String(mesg2) + "");

console.log(mesg3);

console.log("\xe4\xbd\xa0\xe5\xa5\xbd\xe4\xb8\x96\xe7\x95\x8c\xef\xbc\x81");

var john = {
  name: "John",
  age: 34,
  job: "Cyborg Mechnanic"
};

console.log(john);

exports.mesg = mesg;
exports.mesg2 = mesg2;
exports.mesg3 = mesg3;
exports.john = john;
/* mesg Not a pure module */
