// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function prettyStringify(json) {
  return JSON.stringify(json, null, 2);
}

exports.prettyStringify = prettyStringify;
/* No side effect */
