// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var response = (
{
  name: 555,
  age: 123
}
);

function user(json) {
  return /* record */Block.record([
            "name",
            "age"
          ], [
            Json_decode.field("name", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("age", Json_decode.$$int, json)
          ]);
}

var Decode = /* module */Block.localModule(["user"], [user]);

console.log(user(response));

exports.response = response;
exports.Decode = Decode;
/* response Not a pure module */
