// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("bs-json/src/Json.js");
var Json_decode = require("bs-json/src/Json_decode.js");

var text = "\n{\n    \"name\": \"Wario\",\n    \"job\": \"Villain\",\n    \"powerLevel\": 8999.99,\n    \"bio\": \"Evil version of Mario\"\n}    \n";

var json = Json.parseOrRaise(text);

console.log(json);

var obj_000 = /* name */Json_decode.field("name", Json_decode.string, json);

var obj_001 = /* job */Json_decode.field("job", Json_decode.string, json);

var obj_002 = /* powerLevel */Json_decode.field("powerLevel", Json_decode.$$float, json);

var obj = /* record */[
  obj_000,
  obj_001,
  obj_002
];

console.log(obj);

console.log(obj_000);

exports.text = text;
exports.json = json;
exports.obj = obj;
/* json Not a pure module */
