// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var response = (
{
  events: [
    {
      name: 'Block Party',
      description: 'Come to a party on my block',
      type: 'party',
      rsvp_count: 7,
      venue: {
        name: 'The Best Block EVAR',
        address: '400-500 N Groob Ln'
      }
    },
    {
      name: 'Harvest Parade',
      description: 'A wonderful parade featuring tomatoes and potatoes',
      type: 'parade',
      rsvp_count: 305
    }
  ]
}
);

function venue(json) {
  return /* record */Block.record([
            "name",
            "address"
          ], [
            Json_decode.field("name", Json_decode.string, json),
            Json_decode.field("address", Json_decode.string, json)
          ]);
}

function $$event(json) {
  return /* record */Block.record([
            "name",
            "description",
            "type_",
            "rsvp_count",
            "venue"
          ], [
            Json_decode.field("name", Json_decode.string, json),
            Json_decode.field("description", Json_decode.string, json),
            Json_decode.field("type", Json_decode.string, json),
            Json_decode.field("rsvp_count", Json_decode.$$int, json),
            Json_decode.optional((function (param) {
                    return Json_decode.field("venue", venue, param);
                  }), json)
          ]);
}

var Decode = /* module */Block.localModule([
    "venue",
    "event"
  ], [
    venue,
    $$event
  ]);

$$Array.iter((function (evt) {
        console.log(evt[/* name */0]);
        var match = evt[/* venue */4];
        if (match !== undefined) {
          console.log("At " + match[/* name */0]);
        } else {
          console.log("Venue unknown");
        }
        console.log("====");
        return /* () */0;
      }), Json_decode.array($$event, response.events));

exports.response = response;
exports.Decode = Decode;
/* response Not a pure module */
