// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var response = (
{
  name: 555,
  age: 123
}
);

function user(json) {
  return {
          name: Json_decode.field("name", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          age: Json_decode.field("age", Json_decode.$$int, json)
        };
}

var Decode = {
  user: user
};

console.log(user(response));

exports.response = response;
exports.Decode = Decode;
/* response Not a pure module */
