// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function sleep(ms) {
  return new Promise((function (resolve, _reject) {
                setTimeout((function (param) {
                        return resolve(/* () */0);
                      }), ms);
                return /* () */0;
              }));
}

var __x = Promise.all(Belt_List.toArray(Belt_List.map(/* :: */[
              1000,
              /* :: */[
                1200,
                /* :: */[
                  1500,
                  /* :: */[
                    2000,
                    /* :: */[
                      100,
                      /* :: */[
                        3000,
                        /* :: */[
                          4000,
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ], (function (n) {
                console.log("Will sleep for " + (String(n) + " milliseconds..."));
                return Promise.resolve(sleep(n).then((function (param) {
                                  return Promise.resolve((console.log("Slept " + (String(n) + " milliseconds!")), /* () */0));
                                })));
              }))));

__x.then((function (param) {
        return Promise.resolve((console.log("All done!"), /* () */0));
      }));

var P = 0;

exports.P = P;
exports.sleep = sleep;
/* __x Not a pure module */
