// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var value = Math.max(1, Math.log(2) / Math.log(3));

console.log(value);

exports.value = value;
/* value Not a pure module */
