// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

console.log("__LOC__:", "File \"MagicVariables.re\", line 1, characters 20-27");

console.log("__FILE__:", "MagicVariables.re");

console.log("__MODULE__:", "MagicVariables-HelloReason");

console.log("__LINE__:", 7);

console.log("__MODULE__ inside InnerModule:", "MagicVariables-HelloReason");

var InnerModule = /* module */Block.localModule([], []);

exports.InnerModule = InnerModule;
/*  Not a pure module */
