// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';


console.log("__LOC__:", "File \"/Users/fhsu/work/reason-quickstart/src/MagicVariables.re\", line 1, characters 20-27");

console.log("__FILE__:", "/Users/fhsu/work/reason-quickstart/src/MagicVariables.re");

console.log("__MODULE__:", "MagicVariables-HelloReason");

console.log("__LINE__:", 7);

console.log("__MODULE__ inside InnerModule:", "MagicVariables-HelloReason");

var InnerModule = /* module */[];

exports.InnerModule = InnerModule;
/*  Not a pure module */
