// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function compare(param, param$1) {
  var c = Caml_obj.caml_compare(param[0], param$1[0]);
  if (c !== 0) {
    return c;
  } else {
    return Caml_obj.caml_compare(param[1], param$1[1]);
  }
}

var IntPairs = /* module */[/* compare */compare];

var PairsMap = $$Map.Make(IntPairs);

var m = Curry._3(PairsMap[/* add */3], /* tuple */[
      1,
      0
    ], "world", Curry._3(PairsMap[/* add */3], /* tuple */[
          0,
          1
        ], "hello", PairsMap[/* empty */0]));

console.log(Curry._2(PairsMap[/* find */21], /* tuple */[
          1,
          0
        ], m));

var exit = 0;

var value;

try {
  value = Curry._2(PairsMap[/* find */21], /* tuple */[
        0,
        0
      ], m);
  exit = 1;
}
catch (exn){
  if (exn === Caml_builtin_exceptions.not_found) {
    console.log("Key was not found");
  } else {
    throw exn;
  }
}

if (exit === 1) {
  console.log(value);
}

exports.IntPairs = IntPairs;
exports.PairsMap = PairsMap;
exports.m = m;
/* PairsMap Not a pure module */
