// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var arr = Belt_Array.range(1, 10);

console.log("Using the pizza (reverse application) operator:");

console.log(Belt_Array.map(arr, (function (x) {
            return (x << 1);
          })));

console.log("Using the golf club (fast pipe) operator:");

console.log(Belt_Array.map(arr, (function (x) {
            return x + 1 | 0;
          })));

exports.arr = arr;
/* arr Not a pure module */
