// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Set = require("bs-platform/lib/js/belt_Set.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

var cmp = Caml_obj.caml_compare;

var Comparable = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

var set = Belt_Set.fromArray(/* array */[
      /* Foo */3505894,
      /* Bar */3303859,
      /* Baz */3303867,
      /* Burger */219710165
    ], Comparable);

console.log("Full set:");

Belt_List.forEach(/* :: */[
      /* Foo */3505894,
      /* :: */[
        /* Bar */3303859,
        /* :: */[
          /* Baz */3303867,
          /* :: */[
            /* Burger */219710165,
            /* [] */0
          ]
        ]
      ]
    ], (function (e) {
        console.log(e, Belt_Set.has(set, e));
        return /* () */0;
      }));

var emptySet = Belt_Set.make(Comparable);

console.log("Empty set:");

Belt_List.forEach(/* :: */[
      /* Foo */3505894,
      /* :: */[
        /* Bar */3303859,
        /* :: */[
          /* Baz */3303867,
          /* :: */[
            /* Burger */219710165,
            /* [] */0
          ]
        ]
      ]
    ], (function (e) {
        console.log(e, Belt_Set.has(emptySet, e));
        return /* () */0;
      }));

exports.Comparable = Comparable;
exports.set = set;
exports.emptySet = emptySet;
/* Comparable Not a pure module */
