// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Set = require("bs-platform/lib/js/belt_Set.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var cmp = Caml_obj.caml_compare;

var Comparable = Belt_Id.MakeComparable({
      cmp: cmp
    });

var set = Belt_Set.fromArray(/* array */[
      /* Foo */3505894,
      /* Bar */3303859,
      /* Baz */3303867,
      /* Burger */219710165
    ], Comparable);

console.log("Full set:");

Belt_List.forEach(/* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* Foo */3505894,
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* Bar */3303859,
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                /* Baz */3303867,
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    /* Burger */219710165,
                    /* [] */0
                  ])
              ])
          ])
      ]), (function (e) {
        console.log(e, Belt_Set.has(set, e));
        return /* () */0;
      }));

var emptySet = Belt_Set.make(Comparable);

console.log("Empty set:");

Belt_List.forEach(/* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* Foo */3505894,
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* Bar */3303859,
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                /* Baz */3303867,
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    /* Burger */219710165,
                    /* [] */0
                  ])
              ])
          ])
      ]), (function (e) {
        console.log(e, Belt_Set.has(emptySet, e));
        return /* () */0;
      }));

exports.Comparable = Comparable;
exports.set = set;
exports.emptySet = emptySet;
/* Comparable Not a pure module */
