// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function evenPromise(num) {
  return new Promise((function (resolve, reject) {
                var match = num % 2 === 0;
                if (match) {
                  return resolve(num);
                } else {
                  return reject([
                              Caml_builtin_exceptions.failure,
                              "Not an even number"
                            ]);
                }
              }));
}

var unusedPromise = Promise.resolve(5);

evenPromise(2).catch((function (err) {
        console.log(err);
        return Promise.resolve(-1);
      }));

evenPromise(3).catch((function (err) {
        console.log(err);
        return Promise.resolve(-1);
      }));

evenPromise(4).then((function (value) {
          var match = value === 4;
          if (match) {
            return Pervasives.failwith("exception!");
          } else {
            return Promise.resolve(value);
          }
        })).catch((function (err) {
        console.log(err);
        return Promise.resolve(-1);
      }));

evenPromise(7).catch((function (err) {
        if (err[0] === Caml_builtin_exceptions.failure) {
          console.log("After coercion to exn: " + err[1]);
        } else {
          console.log("Unknown type of error");
        }
        return Promise.resolve(-1);
      }));

exports.evenPromise = evenPromise;
exports.unusedPromise = unusedPromise;
/* unusedPromise Not a pure module */
