// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var myPromise = new Promise((function (resolve, _) {
        return resolve(2);
      }));

myPromise.then((function (value) {
          return Promise.resolve(value);
        })).catch((function (err) {
        console.log(err);
        return Promise.resolve(0);
      }));

myPromise.then((function (value) {
          var match = value === 2;
          if (match) {
            return Promise.reject([
                        Caml_builtin_exceptions.failure,
                        "rejection!"
                      ]);
          } else {
            return Promise.resolve(value);
          }
        })).catch((function (err) {
        console.log(err);
        return Promise.resolve(0);
      }));

myPromise.then((function (value) {
          var match = value === 2;
          if (match) {
            return Pervasives.failwith("exception!");
          } else {
            return Promise.resolve(value);
          }
        })).catch((function (err) {
        console.log(err);
        return Promise.resolve(0);
      }));

exports.myPromise = myPromise;
/* myPromise Not a pure module */
