// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';


var state_001 = /* someInstanceVar : record */[/* contents */2];

var state = /* record */[
  /* a */1,
  state_001
];

var state2_001 = state_001;

var state2 = /* record */[
  /* a */3,
  state2_001
];

state_001[0] = 44;

console.log(state2_001[0]);

exports.state = state;
exports.state2 = state2;
/*  Not a pure module */
