// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var state_someInstanceVar = {
  contents: 2
};

var state = {
  a: 1,
  someInstanceVar: state_someInstanceVar
};

var state2_someInstanceVar = state_someInstanceVar;

var state2 = {
  a: 3,
  someInstanceVar: state2_someInstanceVar
};

state_someInstanceVar.contents = 44;

console.log(state2_someInstanceVar.contents);

exports.state = state;
exports.state2 = state2;
/*  Not a pure module */
