// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Set = require("bs-platform/lib/js/belt_Set.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function cmp(param, param$1) {
  var c = Caml_obj.caml_compare(param[0], param$1[0]);
  if (c !== 0) {
    return c;
  } else {
    return Caml_obj.caml_compare(param[1], param$1[1]);
  }
}

var IntPairs = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

var set = Belt_Set.make(IntPairs);

console.log(Belt_Set.toList(Belt_Set.remove(Belt_Set.add(Belt_Set.add(Belt_Set.add(Belt_Set.add(set, /* tuple */[
                              0,
                              0
                            ]), /* tuple */[
                          1,
                          2
                        ]), /* tuple */[
                      1,
                      3
                    ]), /* tuple */[
                  0,
                  0
                ]), /* tuple */[
              1,
              2
            ])));

exports.IntPairs = IntPairs;
exports.set = set;
/* IntPairs Not a pure module */
