// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function crazyFunc (text){
  switch(text) {
    case 'string':
      return 'hello world'
    case 'float':
      return 999.999
    case 'int':
      return 42
    case 'true':
      return true
    case 'false':
      return false
    case 'null':
      return null
    default:
      return {name: 'Cassidy', job: 'adventurer'}
  }
};

Belt_List.forEach(Belt_List.map(/* :: */Block.simpleVariant("::", [
            "string",
            /* :: */Block.simpleVariant("::", [
                "float",
                /* :: */Block.simpleVariant("::", [
                    "int",
                    /* :: */Block.simpleVariant("::", [
                        "true",
                        /* :: */Block.simpleVariant("::", [
                            "false",
                            /* :: */Block.simpleVariant("::", [
                                "null",
                                /* :: */Block.simpleVariant("::", [
                                    "whatever",
                                    /* [] */0
                                  ])
                              ])
                          ])
                      ])
                  ])
              ])
          ]), (function (v) {
            var match = Js_json.classify(crazyFunc(v));
            if (typeof match === "number") {
              switch (match) {
                case 0 : 
                    return /* `Bool */Block.polyVar("Bool", [
                              737456202,
                              false
                            ]);
                case 1 : 
                    return /* `Bool */Block.polyVar("Bool", [
                              737456202,
                              true
                            ]);
                case 2 : 
                    return /* Null */870828711;
                
              }
            } else {
              switch (match.tag | 0) {
                case 0 : 
                    return /* `String */Block.polyVar("String", [
                              -976970511,
                              match[0]
                            ]);
                case 1 : 
                    return /* `Float */Block.polyVar("Float", [
                              365180284,
                              match[0]
                            ]);
                case 2 : 
                    return /* `Object */Block.polyVar("Object", [
                              -908856609,
                              match[0]
                            ]);
                case 3 : 
                    return Pervasives.failwith("Unexpected type");
                
              }
            }
          })), (function (v) {
        console.log(v);
        return /* () */0;
      }));

exports.crazyFunc = crazyFunc;
/*  Not a pure module */
