// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function crazyFunc (text){
  switch(text) {
    case 'string':
      return 'hello world'
    case 'float':
      return 999.999
    case 'int':
      return 42
    case 'true':
      return true
    case 'false':
      return false
    case 'null':
      return null
    default:
      return {name: 'Cassidy', job: 'adventurer'}
  }
};

Belt_List.forEach(Belt_List.map(/* :: */[
          "string",
          /* :: */[
            "float",
            /* :: */[
              "int",
              /* :: */[
                "true",
                /* :: */[
                  "false",
                  /* :: */[
                    "null",
                    /* :: */[
                      "whatever",
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ], (function (v) {
            var match = Js_json.classify(crazyFunc(v));
            if (typeof match === "number") {
              switch (match) {
                case 0 : 
                    return /* `Bool */[
                            737456202,
                            false
                          ];
                case 1 : 
                    return /* `Bool */[
                            737456202,
                            true
                          ];
                case 2 : 
                    return /* Null */870828711;
                
              }
            } else {
              switch (match.tag | 0) {
                case 0 : 
                    return /* `String */[
                            -976970511,
                            match[0]
                          ];
                case 1 : 
                    return /* `Float */[
                            365180284,
                            match[0]
                          ];
                case 2 : 
                    return /* `Object */[
                            -908856609,
                            match[0]
                          ];
                case 3 : 
                    return Pervasives.failwith("Unexpected type");
                
              }
            }
          })), (function (v) {
        console.log(v);
        return /* () */0;
      }));

exports.crazyFunc = crazyFunc;
/*  Not a pure module */
