// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

function fruitToJs(param) {
  return param + 0 | 0;
}

function fruitFromJs(param) {
  if (param <= 3 && 0 <= param) {
    return /* Some */[param - 0 | 0];
  } else {
    return /* None */0;
  }
}

console.log(1);

console.log(Caml_obj.caml_equal(fruitFromJs(2), /* Some */[/* Kiwi */2]));

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -943000342,
    "Tomato"
  ],
  /* tuple */[
    -773071970,
    "Lettuce"
  ],
  /* tuple */[
    -653145215,
    "Cabbage"
  ],
  /* tuple */[
    420197030,
    "Eggplant"
  ],
  /* tuple */[
    890286854,
    "Cucumber"
  ]
];

function veggieToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray);
}

function veggieFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray, param);
}

console.log(veggieToJs(/* Lettuce */-773071970));

console.log(Caml_obj.caml_equal(veggieFromJs("Eggplant"), /* Some */[/* Eggplant */420197030]));

exports.fruitToJs = fruitToJs;
exports.fruitFromJs = fruitFromJs;
exports.veggieToJs = veggieToJs;
exports.veggieFromJs = veggieFromJs;
/*  Not a pure module */
