// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");

describe("Expect", (function () {
        Jest.test("Addition", (function () {
                return Jest.Expect[/* toBe */2](7, Jest.Expect[/* expect */0](7));
              }));
        return Jest.test("Subtraction", (function () {
                      return Jest.Expect[/* toBe */2](-61, Jest.Expect[/* expect */0](-61));
                    }));
      }));

/*  Not a pure module */
