// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Euler1$HelloReason = require("../src/Euler1.bs.js");

describe("Expect", (function (param) {
        Jest.test("Addition", (function (param) {
                return Jest.Expect.toBe(7, Jest.Expect.expect(7));
              }));
        Jest.test("Subtraction", (function (param) {
                return Jest.Expect.toBe(-61, Jest.Expect.expect(-61));
              }));
        Jest.test("Concatenation", (function (param) {
                return Jest.Expect.toBe("abcd", Jest.Expect.expect("abcd"));
              }));
        return Jest.test("Project Euler #1", (function (param) {
                      return Jest.Expect.toBe(233168, Jest.Expect.expect(Euler1$HelloReason.compute(/* () */0)));
                    }));
      }));

/*  Not a pure module */
