// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

describe("Belt.List", (function (param) {
        Jest.test("make", (function (param) {
                return Jest.Expect.toEqual(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                              /* "A" */65,
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  /* "A" */65,
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      /* "A" */65,
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          /* "A" */65,
                                          /* [] */0
                                        ])
                                    ])
                                ])
                            ]), Jest.Expect.expect(Belt_List.make(4, /* "A" */65)));
              }));
        Jest.test("makeBy", (function (param) {
                return Jest.Expect.toEqual(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                              0,
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  2,
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      4,
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          6,
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              8,
                                              /* [] */0
                                            ])
                                        ])
                                    ])
                                ])
                            ]), Jest.Expect.expect(Belt_List.makeBy(5, (function (i) {
                                      return (i << 1);
                                    }))));
              }));
        Jest.test("getAssoc", (function (param) {
                return Jest.Expect.toEqual("b", Jest.Expect.expect(Belt_List.getAssoc(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      /* tuple */[
                                        1,
                                        "a"
                                      ],
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          /* tuple */[
                                            2,
                                            "b"
                                          ],
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              /* tuple */[
                                                3,
                                                "c"
                                              ],
                                              /* [] */0
                                            ])
                                        ])
                                    ]), 2, (function (prim, prim$1) {
                                      return prim === prim$1;
                                    }))));
              }));
        Jest.test("zip", (function (param) {
                return Jest.Expect.toEqual(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                              /* tuple */[
                                1,
                                /* "a" */97
                              ],
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  /* tuple */[
                                    2,
                                    /* "b" */98
                                  ],
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      /* tuple */[
                                        3,
                                        /* "c" */99
                                      ],
                                      /* [] */0
                                    ])
                                ])
                            ]), Jest.Expect.expect(Belt_List.zip(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      1,
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          2,
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              3,
                                              /* [] */0
                                            ])
                                        ])
                                    ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      /* "a" */97,
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          /* "b" */98,
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              /* "c" */99,
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  /* "d" */100,
                                                  /* [] */0
                                                ])
                                            ])
                                        ])
                                    ]))));
              }));
        return Jest.test("zipBy", (function (param) {
                      return Jest.Expect.toEqual(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    /* tuple */[
                                      3,
                                      /* "a" */97
                                    ],
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        /* tuple */[
                                          6,
                                          /* "b" */98
                                        ],
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            /* tuple */[
                                              9,
                                              /* "c" */99
                                            ],
                                            /* [] */0
                                          ])
                                      ])
                                  ]), Jest.Expect.expect(Belt_List.zipBy(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            1,
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                2,
                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                    3,
                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                        4,
                                                        /* [] */0
                                                      ])
                                                  ])
                                              ])
                                          ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            /* "a" */97,
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                /* "b" */98,
                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                    /* "c" */99,
                                                    /* [] */0
                                                  ])
                                              ])
                                          ]), (function (x, y) {
                                            return /* tuple */[
                                                    Caml_int32.imul(x, 3),
                                                    y
                                                  ];
                                          }))));
                    }));
      }));

/*  Not a pure module */
